base_images:
  cli:
    name: "4.13"
    namespace: ocp
    tag: cli
  os:
    name: ubi
    namespace: ocp
    tag: "8"
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.19
images:
- context_dir: .
  dockerfile_path: dockerfiles/interop/Dockerfile
  to: test-gitops-ref
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.13"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: redhat-openshift-gitops-interop-aws
  cron: 0 1 * * 1
  steps:
    cluster_profile: aws-cspi-qe
    env:
      BASE_DOMAIN: cspilp.interop.ccitredhat.com
      OPERATORS: |
        [
            {"name": "openshift-gitops-operator", "source": "redhat-operators", "channel": "stable", "install_namespace": "openshift-operators", "target_namespaces": "", "operator_group": "global-operators"}
        ]
      SPOT_INSTANCES: "true"
    test:
    - ref: install-operators
    workflow: ipi-aws
zz_generated_metadata:
  branch: master
  org: redhat-developer
  repo: gitops-operator
  variant: gitops-ocp4.13-lp-interop
