base_images:
  os:
    name: centos
    namespace: openshift
    tag: stream9
build_root:
  from_repository: true
images:
- dockerfile_path: prow/Dockerfile
  from: os
  to: krkn-hub-414-x86-64
releases:
  initial:
    integration:
      name: "4.14"
      namespace: ocp
  latest:
    integration:
      include_built_images: true
      name: "4.14"
      namespace: ocp
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: krkn-hub-tests-x86-64
  cron: 0 8 */2 * *
  steps:
    cluster_profile: aws
    env:
      CONTROL_PLANE_INSTANCE_TYPE: m5.2xlarge
      OCP_ARCH: x86_64
      SPOT_INSTANCES: "true"
    post:
    - chain: ipi-aws-post
    pre:
    - chain: ipi-aws-pre
    - chain: create-infra-move-ingress-monitoring-registry
    test:
    - chain: redhat-chaos-krkn-hub-tests
<<<<<<< HEAD
<<<<<<< HEAD
=======
    - chain: redhat-chaos-pvc-scenarios
>>>>>>> 0c2f2b459c8 (Enable hog scenarios for 4.14 (#43278))
=======
>>>>>>> d663a3c1df0 (Add etcd service disruption chaos scenario (#43176))
    - chain: redhat-chaos-hog-scenarios
zz_generated_metadata:
  branch: main
  org: redhat-chaos
  repo: krkn-hub
  variant: 4.14-nightly-x86-64
