binary_build_commands: go build -o /bin/prune .
build_root:
  from_repository: true
images:
- dockerfile_literal: FROM bin
  from: bin
  to: shiftstack-prune-image
resources:
  '*':
    limits:
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: go-fmt
<<<<<<< HEAD
<<<<<<< HEAD
  commands: if [ "$(go fmt ./... | tee /dev/stderr | wc -l)" -gt 0 ]; then exit 1;
=======
  commands: if [ "$(gofmt -s -l . | tee /dev/stderr | wc -l)" -gt 0 ]; then exit 1;
>>>>>>> 813fa0def84 (openstack: Add repository shiftstack/prune (#43294))
=======
  commands: if [ "$(go fmt ./... | tee /dev/stderr | wc -l)" -gt 0 ]; then exit 1;
>>>>>>> 7ce115b99ac (shiftstack/prune: Ignore vendor when checking go fmt (#43352))
    fi
  container:
    from: src
- as: go-vet
  commands: go vet ./...
  container:
    from: src
zz_generated_metadata:
  branch: main
  org: shiftstack
  repo: prune
