base_images:
  cli:
    name: "4.13"
    namespace: ocp
    tag: cli
  ocp-addons-operators-cli:
    name: ocp-addons-operators-cli
    namespace: ci
    tag: latest
  openshift-cli-installer:
    name: openshift-cli-installer
    namespace: ci
    tag: latest
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.19
releases:
  latest:
    candidate:
      product: ocp
      stream: ci
      version: "4.13"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 200m
      memory: 200Mi
tests:
- as: rosa-sts-test-operator-use-installer
  cron: 0 6 * * 1
  steps:
    cluster_profile: aws-cspi-qe
    env:
      CLUSTER1_CONFIG: name=rosa-rhods;platform=rosa;region=us-east-2;version=4.13;channel-group=stable;compute-machine-type=m5.4xlarge;timeout=90m;replicas=2;fips=true;ocm-env=stage
      FIREWATCH_CONFIG: |
        [
          {"step": "operator-install", "failure_type": "all", "classification": "Provisioning - Operators", "jira_project": "LPTOCPCI"},
          {"step": "cluster-install-*", "failure_type": "all", "classification":  "Cluster Creation - ROSA", "jira_project": "LPTOCPCI", "group": {"name": "cluster-provision", "priority": 1}},
          {"step": "cluster-uninstall-*", "failure_type": "all", "classification":  "Cluster Creation - ROSA", "jira_project": "LPTOCPCI", "group": {"name": "cluster-provision", "priority": 2}}
        ]
      FIREWATCH_DEFAULT_JIRA_PROJECT: LPTOCPCI
      FIREWATCH_JIRA_SERVER: https://issues.redhat.com
      OPENSHIFT_VERSION: "4.13"
      #OPERATOR1_CONFIG: name=rhods-operator;namespace=redhat-ods-operator; timeout=600
      PULL_SECRET_NAME: cluster-secrets
      S3_BUCKET_NAME: openshift-cli-installer
      S3_BUCKET_PATH: openshift-ci
    workflow: operator
zz_generated_metadata:
  branch: main
  org: rhpit
  repo: interop-tests
  variant: rosa-sts-test-operator-ocp4.13-lp-interop
