label:
  restricted_labels:
    openshift/openshift-controller-manager:
    - allowed_users:
      - akram
      - coreydaley
      - ingvagabund
      - soltysh
      - stlaz
      - sttts
      - s-urbaniak
      - tkashem
      label: backport-risk-assessed
    - allowed_users:
      - jitendar-singh
      - prietyc123
      - xingxingxia
      - wangke19
      - gangwgr
<<<<<<< HEAD
      - kasturinarra
      - zhouying7780
=======
      - knarra
      - yinzhou
>>>>>>> c89acba5e06 (Extend permissions to more users so that they could add cherry-pick-approved labels (#43361))
      label: cherry-pick-approved
plugins:
  openshift/openshift-controller-manager:
    plugins:
    - approve
