label:
  restricted_labels:
    openshift/cluster-openshift-controller-manager-operator:
    - allowed_users:
      - akram
      - coreydaley
      - ingvagabund
      - soltysh
      - sttts
      - s-urbaniak
      - tkashem
      label: backport-risk-assessed
    - allowed_users:
      - jitendar-singh
      - prietyc123
<<<<<<< HEAD
<<<<<<< HEAD
      - kasturinarra
      - zhouying7780
=======
      - knarra
      - yinzhou
>>>>>>> c89acba5e06 (Extend permissions to more users so that they could add cherry-pick-approved labels (#43361))
=======
      - kasturinarra
      - zhouying7780
>>>>>>> 176a88725c1 (Correcting user names (#43374))
      label: cherry-pick-approved
plugins:
  openshift/cluster-openshift-controller-manager-operator:
    plugins:
    - approve
