build_root:
  project_image:
    dockerfile_path: .ci/openshift-ci/Dockerfile
images:
<<<<<<< HEAD
<<<<<<< HEAD
- dockerfile_path: .ci/openshift-ci/build/Dockerfile
=======
- dockerfile_path: build/dockerfiles/Dockerfile
>>>>>>> 2184f5f1d7b (Update ci job for che-plugin-registry repo (#43296))
=======
- dockerfile_path: .ci/openshift-ci/build/Dockerfile
>>>>>>> b6e186adfbd (Fix path to the Dockerfile for plugin reg ci build (#43403))
  to: che-plugin-registry
releases:
  initial:
    integration:
      name: "4.12"
      namespace: ocp
  latest:
    integration:
      include_built_images: true
      name: "4.12"
      namespace: ocp
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: plugins-test-pr-check
  steps:
    cluster_profile: gcp
    test:
    - as: plugins-pr-check
      cli: latest
      commands: |
        /bin/bash .ci/openshift-ci/smoke-test.sh
      dependencies:
      - env: CHE_PLUGIN_REGISTRY
        name: che-plugin-registry
      from: src
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
    workflow: ipi-gcp
zz_generated_metadata:
  branch: main
  org: eclipse-che
  repo: che-plugin-registry
  variant: v12
