base_images:
  cli:
    name: "4.14"
    namespace: ocp
    tag: cli
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.19
images:
- context_dir: .
  dockerfile_path: Dockerfile
  to: maistra-runner
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.14"
resources:
  '*':
    limits:
      memory: 8Gi
    requests:
      cpu: "1"
      memory: 4Gi
tests:
- as: servicemesh-rosa-aws
  cron: 0 6 25 10 *
  steps:
    cluster_profile: aws-cspi-qe
    env:
      FIREWATCH_CONFIG: |
        [
          {"step": "aws-provision*", "failure_type": "all", "classification": "Infrastructure Provisioning - AWS", "jira_project": "LPTOCPCI", "group": {"name": "cluster", "priority": 1}, "jira_additional_labels": ["4.14-lp","rosa-lp","servicemesh-lp"]},
          {"step": "aws-deprovision*", "failure_type": "all", "classification": "Infrastructure Deprovisioning - AWS", "jira_project": "LPTOCPCI", "group": {"name": "cluster", "priority": 2}, "jira_additional_labels": ["4.14-lp","rosa-lp","servicemesh-lp"]},
          {"step": "cucushift-*", "failure_type": "all", "classification": "Health Check - Cluster", "jira_project": "LPTOCPCI", "group": {"name": "lp-tests", "priority": 2}, "jira_additional_labels": ["4.14-lp","rosa-lp","servicemesh-lp"]},
          {"step": "gather-*", "failure_type": "pod_failure", "classification": "Must Gather - Cluster", "jira_project": "LPTOCPCI", "group": {"name": "cluster", "priority": 3}, "jira_additional_labels": ["4.14-lp","rosa-lp","servicemesh-lp"]},
          {"step": "gather-*", "failure_type": "test_failure", "classification": "NONE", "jira_project": "NONE", "ignore": "true"},
          {"step": "install-operators", "failure_type": "all", "classification": "Infrastructure Provisioning - Operators", "jira_project": "LPTOCPCI", "group": {"name": "lp-tests", "priority": 1}, "jira_additional_labels": ["4.14-lp","rosa-lp","servicemesh-lp"]},
          {"step": "openshift-*", "failure_type": "all", "classification": "Other", "jira_project": "LPTOCPCI", "group": {"name": "cluster", "priority": 2}, "jira_additional_labels": ["4.14-lp","rosa-lp","servicemesh-lp"]},
          {"step": "rosa-cluster-deprovision", "failure_type": "all", "classification": "Infrastructure Deprovisioning - Cluster", "jira_project": "LPTOCPCI", "group": {"name": "cluster", "priority": 2}, "jira_additional_labels": ["4.14-lp","rosa-lp","servicemesh-lp"]},
          {"step": "rosa-cluster-provision", "failure_type": "all", "classification": "Infrastructure Provisioning - Cluster", "jira_project": "LPTOCPCI", "group": {"name": "cluster", "priority": 1}, "jira_additional_labels": ["4.14-lp","rosa-lp","servicemesh-lp"]},
          {"step": "rosa-cluster-wait*", "failure_type": "all", "classification": "Infrastructure Provisioning - Rosa Cluster Operators", "jira_project": "LPTOCPCI", "group": {"name": "cluster", "priority": 2}, "jira_additional_labels": ["4.14-lp","rosa-lp","servicemesh-lp"]},
          {"step": "rosa-sts-account-roles-create", "failure_type": "all", "classification": "Account Roles Creation - AWS", "jira_project": "LPTOCPCI", "group": {"name": "cluster", "priority": 2}, "jira_additional_labels": ["4.14-lp","rosa-lp","servicemesh-lp"]},
          {"step": "rosa-sts-account-roles-delete", "failure_type": "all", "classification": "Account Roles Deletion - AWS", "jira_project": "LPTOCPCI", "group": {"name": "cluster", "priority": 3}, "jira_additional_labels": ["4.14-lp","rosa-lp","servicemesh-lp"]},
          {"step": "rosa-conf-idp-htpasswd", "failure_type": "all", "classification": "Admin Access - Cluster", "jira_project": "LPTOCPCI", "group": {"name": "cluster", "priority": 2}, "jira_additional_labels": ["4.14-lp","rosa-lp","servicemesh-lp"]}
        ]
      FIREWATCH_DEFAULT_JIRA_PROJECT: LPTOCPCI
      FIREWATCH_JIRA_SERVER: https://issues.redhat.com
      OCM_LOGIN_ENV: staging
      OPENSHIFT_VERSION: "4.14"
      OPERATORS: |
        [
            {"name": "servicemeshoperator", "source": "redhat-operators", "channel": "stable", "install_namespace": "openshift-operators"}
        ]
      ROSA_LOGIN_ENV: staging
    test:
    - chain: install-operators
    workflow: firewatch-rosa-aws-sts
zz_generated_metadata:
  branch: main
  org: maistra
  repo: maistra-test-tool
  variant: servicemesh-ocp4.14-lp-rosa
