base_images:
  cli:
    name: "4.13"
    namespace: ocp
    tag: cli
  upi-installer:
    name: "4.13"
    namespace: ocp
    tag: upi-installer
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.18
images:
- dockerfile_path: prow/Dockerfile
  to: ocp-qe-perfscale-ci-aro-4.13-nightly
promotion:
  namespace: ci
  tag: latest
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.13"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
<<<<<<< HEAD:ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aro-4.13-nightly-x86.yaml
- as: perfscale-aro-node-density-cni-6nodes-periodic
=======
- as: ocp-qe-perfscale-node-density-cni-6nodes-aro
>>>>>>> 361eeb34c01 (Rename ocp-qe-perfscale-ci-tests to control-plane (#43253)):ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aro-4.13-nightly.yaml
  cron: 0 12 * * 3
  steps:
    cluster_profile: azure-qe
    env:
      ARO_MASTER_VM_SIZE: Standard_D8s_v3
      ARO_WORKER_COUNT: "6"
      ARO_WORKER_VM_SIZE: Standard_D8s_v3
    test:
    - chain: openshift-qe-node-density-cni
    workflow: openshift-qe-installer-azure-aro
<<<<<<< HEAD:ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aro-4.13-nightly-x86.yaml
- as: perfscale-aro-node-density-heavy-6nodes-periodic
=======
- as: ocp-qe-perfscale-node-density-heavy-6nodes-aro
>>>>>>> 361eeb34c01 (Rename ocp-qe-perfscale-ci-tests to control-plane (#43253)):ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aro-4.13-nightly.yaml
  cron: 0 12 * * 3
  steps:
    cluster_profile: azure-qe
    env:
      ARO_MASTER_VM_SIZE: Standard_D8s_v3
      ARO_WORKER_COUNT: "6"
      ARO_WORKER_VM_SIZE: Standard_D8s_v3
    test:
    - chain: openshift-qe-node-density-heavy
    workflow: openshift-qe-installer-azure-aro
<<<<<<< HEAD:ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aro-4.13-nightly-x86.yaml
- as: perfscale-aro-control-plane-6nodes-periodic
=======
- as: ocp-qe-perfscale-cp-6nodes-aro-periodic
>>>>>>> 361eeb34c01 (Rename ocp-qe-perfscale-ci-tests to control-plane (#43253)):ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aro-4.13-nightly.yaml
  cron: 0 12 * * 4
  steps:
    cluster_profile: azure-qe
    env:
      ARO_MASTER_VM_SIZE: Standard_D8s_v3
      ARO_WORKER_COUNT: "6"
      ARO_WORKER_VM_SIZE: Standard_D8s_v3
      ITERATION_MULTIPLIER_ENV: "9"
    test:
    - chain: openshift-qe-control-plane
    workflow: openshift-qe-installer-azure-aro
zz_generated_metadata:
  branch: main
  org: openshift-qe
  repo: ocp-qe-perfscale-ci
  variant: aro-4.13-nightly-x86
